### PR TITLE
feat: :sparkles: add cycle validation

### PR DESCRIPTION
**Pull request by marcodarko**
Only tree-like structures are allowed.
Not allowed:
(n1) <--> (n1) 
(n1) --> (n2) --> (n1) 
(n1) <-- (n2) <-- (n1)

### CODE REVIEW

**Comment by colleenXu** [comment]
I think the conclusion was to have some more review / testing of this PR, and deploy it after this is done and the demo has passed (12/14)

**Comment by colleenXu** [comment]
still needs work @ariutta @marcodarko will coordinate

**Comment by ariutta** [comment]
For purposes of results assembly, each of the following query graphs would be considered to have one or more cycles (arrows removed because for purposes of results assembly, directionality doesn't matter for defining cycles):

image

**Comment by tokebe** [comment]
Closing as issue has been resolved by https://github.com/biothings/bte_trapi_query_graph_handler/pull/111

**Pull request closed without merging**
