### PR TITLE
do pfocr for creative/pathfinder mode at the end

### PR DESCRIPTION
**Pull request by rjawesome**
https://github.com/biothings/biothings_explorer/issues/847. Runs PFOCR augmentation after all creative results have been created.

### CODE REVIEW

**Comment by colleenXu** [comment]
Will this work with Pathfinder too (`pathfinder-newsystem` branch I guess)? 

Also can you adjust the "development" tab in github so merging this PR won't close the issue?

**Comment by rjawesome** [comment]
@colleenXu 
Currently, pathfinder does not add PFOCR figures. However, I have just added a commit to this PR that should add PFOCR to pathfinder results (should work for any pathfinder branch).

**Comment by colleenXu** [comment]
Hmmm while running Pathfinder queries, I noticed that PFOCR result-augmentation would happen at the end of each template...which added time to execution. 

I think It's good that you adjusted things so PFOCR result-augmentation only runs on pathfinder results at the end (another option is to make it so it doesn't run at all).

**Review by tokebe — CHANGES_REQUESTED** [review]
This PR fails to build because it requires that the `QueryHandlerOptions` type be amended in `packages/types/src/tasks.ts`

**Comment by rjawesome** [comment]
@tokebe Oops, I forgot to make a PR for that. See https://github.com/biothings/biothings_explorer/pull/869

**Review by tokebe — APPROVED** [review]

**Pull request merged**
