### PR TITLE
feat: perform node expansion

### PR DESCRIPTION
**Pull request by ericz1803**
This PR addresses https://github.com/biothings/BioThings_Explorer_TRAPI/issues/366 and https://github.com/biothings/BioThings_Explorer_TRAPI/issues/196. Merge https://github.com/biothings/bte-trapi-workspace/pull/17 to update the bte-trapi-workspace monorepo with the [node-expansion](https://github.com/biothings/node-expansion) module.

Node expansion is performed by taking the original query graph and expand the IDs for each node by replacing the array of IDs with an array of the original IDs along with all of the original ID's descendants. 

For example, the original query will be expanded to the expanded query since   `"DOID:0040001", "DOID:0060526", "DOID:0060525", "DOID:0060527", "DOID:0060528", "DOID:0060529"` are all descendants of `DOID:0060524`. The query will be run as if the user queried with the expanded query graph.

<details>
<summary>
Original Query
</summary>
<br>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": ["DOID:0060524"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
</details>

<details>
<summary>
Expanded Query
</summary>
<br>

```
{
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Disease"
      ],
      "ids": [
        "DOID:0060524",
        "DOID:0040001",
        "DOID:0060526",
        "DOID:0060525",
        "DOID:0060527",
        "DOID:0060528",
        "DOID:0060529"
      ]
    },
    "n1": {
      "categories": [
        "biolink:Gene"
      ]
    }
  },
  "edges": {
    "e01": {
      "subject": "n0",
      "object": "n1"
    }
  }
}
```
</details>

Right now, node expansion is always performed although we might want to consider adding an option to turn it off in case the user wants to make a query using a very general ID such as DOID:4 which can have hundreds of thousands or millions of descendants.

Currently expands GO, DOID, MONDO, CHEBI, and HP ids.

### CODE REVIEW

**Comment by andrewsu** [comment]
@ericz1803 out of curiosity, what would happen if someone used `DOID:4`?  I'm guessing it would fail, but would it fail gracefully, and at what point?

**Comment by ericz1803** [comment]
Yup it does fail. 
First, it performs the expansion to 11003 ids since there are 11002 unique descendants of DOID:4. Then it exits at the EdgeManager when it exceeds the entity cap.

```
  bte:biothings-explorer-trapi:main Expanded ids for node n0: (1 ids -> 11003 ids) +0ms
...
  bte:biothings-explorer-trapi:error_handler QueryAborted: Max number of entities exceeded (1000) in 'e01'
```

**Comment by andrewsu** [comment]
Super, this qualifies as failing gracefully in my book...

**Comment by colleenXu** [comment]
Hmmm....are we interested at all of setting a special cap for the number of descendants to add, per single ID input? (like stopping at 20 or so IDs, or some number below 1000)

**Comment by andrewsu** [comment]
I think leaving it to the overall entity cap is good for now.  I think if the query is including a super general term, the preferred solution is more often going to be to change the query rather than adding any sort of change in the application logic.

**Comment by ericz1803** [comment]
@colleenXu @tokebe @andrewsu This issue should be ready to merge. Let me know if there are any issues. We can also discuss it more at the weekly meeting.

**Comment by colleenXu** [comment]
I have a note to test this, but as lower-priority. 

I think this would involve a lot of manual testing and would involve changing existing features (like the creative-mode templates). So....I don't consider this a quick thing to merge / deploy...

**Comment by colleenXu** [comment]
@ericz1803 To clarify, the "node expansion" behavior only happens to IDs on the QNodes of the original QGraph? AKA "node expansion" isn't done on the IDs used as input for intermediate hops?

And @andrewsu, what is the desired behavior regarding this?

---

Also, I'm going to open another issue for discussing requirements related to these PRs / issues. I think there are some missing pieces...

**Comment by ericz1803** [comment]
Right, it only expands the IDs in the original query, not any of the intermediate nodes.

**Comment by colleenXu** [comment]
@ericz1803 Great, now to wait for Andrew's feedback. 

What ID namespaces are covered (so I know what to test)?

**Comment by ericz1803** [comment]
The supported ontologies right now are `go`, `doid`, `chebi`, `mondo`, `hp`, and `umls`.

**Comment by andrewsu** [comment]
I think the "right" thing to do is to expand intermediate nodes as well.  But, I suspect that this will make results explosion even more of a problem, and we won't have effective ways of dealing with it.  So, I guess my ideal scenario would be to test/merge/deploy the PR as it exists now (only expanding query nodes), and at some point in the future, implement intermediate node expansion as an easily configurable parameter.

**Comment by colleenXu** [comment]
Note that I'm pushing the merges I made with the latest main...since this code hadn't been in-line with main for a while.

**Comment by colleenXu** [comment]
(still editing as I'm testing)

Adjustments?
* can we add a TRAPI-level log (INFO?) for the ID/node-expansion itself? Like the console logs, which are
```
  bte:biothings-explorer-trapi:main Expanded ids for node n0: (1 ids -> 9 ids) +0ms
  bte:biothings-explorer-trapi:main Expanded ids for node n2: (1 ids -> 3 ids) +0ms
```

Questions:
* It looks like we only expand the exact ID that was given on the QNode -> then Node Normalizer is queried to get equivalent IDs. Is this preferable to the other way around (getting equivalent IDs with Node Normalizer, then trying to do the expansion with each equivalent ID)?

**Comment by colleenXu** [comment]
### Question B

When we expand the IDs for a QNode, can we also mutate that QNode so `QNode.is_set: true`? This would allow each result to include all the expanded IDs that are connected to the other Nodes...And I like the way the results look better

<details>
<summary>Comparing results adding `is_set: True` vs the current PR behavior</summary>

This is how I modified the query to use `is_set: True`
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"],
                    "name": "multiple sclerosis",
                    "is_set": true
                },
                "n1": {
		             "categories":["biolink:Gene"]
                },
                "n2": {
                    "ids":["GO:0042552"],
                    "categories":["biolink:BiologicalProcess"],
                    "name": "myelination",
                    "is_set": true
               }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                },
                "e1": {
                    "subject": "n2",
                    "object": "n1"
                }
            }
        }
    }
}
```

This is how the results look with `is_set: True`. I think this looks useful. 

Gene is connected to descendant Disease IDs too
Screen Shot 2022-09-22 at 1 20 07 PM

Gene is connected to descendant BiologicalProcess IDs too
Screen Shot 2022-09-22 at 1 24 47 PM


</details>

**Comment by colleenXu** [comment]
Can someone (@tokebe or @ericz1803) do the merge with main? There's a `src/index.js` conflict with the `const` stuff and I resolved it this way on my local to test....but I don't know if that's correct

```
const utils = require('./utils');
const async = require('async');
const biolink = require('./biolink');
const { getDescendants } = require('@biothings-explorer/node-expansion');
const { getTemplates, supportedLookups } = require('./inferred_mode/template_lookup');
const handleInferredMode = require('./inferred_mode/inferred_mode');
const id_resolver = require('biomedical_id_resolver');
```

**Comment by colleenXu** [comment]
@ericz1803 I'm seeing some issues with the UMLS ID-expansion:

[edit in progress, i'm still testing]

When I expand these "chemical" things, I seem to be getting "descendant" IDs that aren't chemicals. Look at the links to see the UMLS IDs
* [acetylcysteine](https://uts.nlm.nih.gov/uts/umls/concept/C0001047): Based on a quick look at the link, I thought the current PR would retrieve things that seem slightly narrower and are still chemicals like [acetylcysteine magnesium](https://uts.nlm.nih.gov/uts/umls/concept/C4283417) or [acetylcysteine Oral Product](https://uts.nlm.nih.gov/uts/umls/concept/C3207642). Instead, it retrieved 3 "descendant" IDs that seemed to be more distantly related: [Acetylcysteine Ab.IgE](https://uts.nlm.nih.gov/uts/umls/concept/C5548663), [Acetylcysteine IgE | Serum | Allergy](https://uts.nlm.nih.gov/uts/umls/concept/C5549454), and [Acetylcysteine Ab.IgE:ACnc:Pt:Ser:Qn](https://uts.nlm.nih.gov/uts/umls/concept/C5548823)

**Comment by ericz1803** [comment]
@colleenXu I disabled node-expansion for creative-mode and also merged the changes which may have fixed the range error? 

Any update on [Part B](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issuecomment-1255684790)? Is it confirmed that we need to not modify the original query graph and link the expanded ID to the original ID?

**Comment by colleenXu** [comment]
@ericz1803 I'm still having this issue https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255705465

I haven't heard anything about the "Part B" in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issuecomment-1255684790, but Andrew and I will probably discuss this set of issues / PRs during our Monday meeting

**Comment by colleenXu** [comment]
I wonder if there's an issue with CHEBI ID expansion. 

When I query using `CHEBI:8382` (prednisone), the current PRs retrieve 1 descendant (for 2 IDs on that QNode going forward): CHEBI:66868 (carboxyspermidine). This is unexpected. 

The webpage for [CHEBI:66868 (carboxyspermidine)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:66868) says that "it is a prednisone" according to the CHEBI ontology. However, the webpage for [CHEBI:8382 (prednisone)](https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=8382) has a "related structures" section where the prednisone is the "functional parent" of 6 other structures that seem to make sense as "descendants". 

<details>
<summary>Query using prednisone</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["CHEBI:8382"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}
```

</details>

**Comment by andrewsu** [comment]
> I wonder if there's an issue with CHEBI ID expansion.
> 
> When I query using CHEBI:8382 (prednisone), the current PRs retrieve 1 descendant (for 2 IDs on that QNode going forward): CHEBI:66868 (carboxyspermidine). This is kinda unexpected from my chem-point-of-view.
> 
> The webpage for [CHEBI:66868 (carboxyspermidine)](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:66868) says that "it is a prednisone" according to the CHEBI ontology. However, the webpage for [CHEBI:8382 (prednisone)](https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=8382) has a "related structures" section where the prednisone is the "functional parent" of 6 other structures that seem to make sense as "descendants".

Yeah I agree, that's pretty weird.  But, if anything that's an issue with ChEBI and not the logic of the node expansion.  So I think this issue should _not_ hold up deployment of this new feature.

Regarding the "Part B" formatting -- no consensus yet, and not likely to be one for a while.  So as long as we're doing something reasonable, I also don't think this should hold anything up.  

The two things that _might_ hold up deployment would be:
* The [RangeError](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255705465) issue: @ericz1803 can you reproduce it with the query Colleen provided?
* Colleen's comment that "Creative-mode now proceeds, but ID/node-expansion is automatically happening as the templates get set up and run."  Am I reading it right that node expansion is actually running in creative mode after all?  I think the current desired behavior is that node expansion does _not_ run in those cases...

**Comment by ericz1803** [comment]
- I tried the query again and I haven't been able to reproduce the RangeError. 
- The node-expansion should be completely disabled for creative-mode. @colleenXu Is there a sample creative-mode query that I can check the behavior with?

I'll work on an implementation for Part B when I get the chance.

**Comment by colleenXu** [comment]
Making 2 new posts to organize all of the information in my posts (starting [here](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255488128)).

## Notes

- I wondered how ID-expansion would affect our [current](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/196#issuecomment-910032722) behavior of dropping records from TRAPI KPs when those KPs did ID-expansion (giving us Edges that don't have the original entity as subject/object). After some thinking, I think the PR code would change this behavior because we would be able to match Edges using the descendant IDs. So that's another benefit of this set of PRs. 

## Testing done

- Creative-mode. See the next post, Problems section. 
- MONDO. Tested queries in the [linked](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issue-1359693815) [issues](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/366#issuecomment-1255506397)
- HP. Tested queries in the [linked](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issue-1359693815) [issues](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/196#issuecomment-1255530559)
- GO BP. Tested query in this [issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/366#issuecomment-1255506397)
- Also tried BiologicalProcess GO:0002352 ([B cell negative selection](http://amigo.geneontology.org/amigo/term/GO:0002352#display-lineage-tab)) -> Disease. GO:0002352 (B cell negative selection) expanded to 3 IDs total, and the[ descendants](http://amigo.geneontology.org/amigo/term/GO:0002352) were correct. 
- GO MF. Tested: MolecularActivity GO:0140104 ([molecular carrier activity](http://amigo.geneontology.org/amigo/term/GO:0140104#display-lineage-tab)) -> Gene
- GO CC. Tested: CellularComponent GO:0005576 ([extracellular region](http://amigo.geneontology.org/amigo/term/GO:0005576#display-lineage-tab)) -> Gene. Notice this sub-ontology doesn't have any is-a relations (instead there's a lot of part-of). 
- DOID. Tested: [DOID:10123](https://disease-ontology.org/?id=DOID:3138) (skin pigmentation disease) -> Gene. Correctly expands to 15 IDs total (14 descendants). 
- CHEBI. Noticed an issue when testing; see the next post, Problems section. 
- Tried SmallMolecule CHEBI:78053 (docosapentaenoate) -> Gene. CHEBI:78053 (docosapentaenoate) expands to 3 IDs total (2 descendants). The descendants make sense: CHEBI:77224 ((7Z,10Z,13Z,16Z,19Z)-docosapentaenoate) and CHEBI:77226 ((4Z,7Z,10Z,13Z,16Z)-docosapentaenoate)
- UMLS: Noticed an issue when testing; see the next post, Problems section. 

## Testing not done

- More UMLS? (but there are a lot of semantic-types, so it'd be a lot of test them all)

**Comment by colleenXu** [comment]
Next post organizing stuff.

## Questions

- Just checking: based on the console-logs, it looks like the ID-expansion happens first (on the IDs provided initially in the query), then equivalent IDs are retrieved (Node Normalizer query). Do we prefer this order? 
- I notice that the console-logs for ID expansion are very early, before the `Start to load metakg` log or `(1) Creating edges for manager` log. Is that expected behavior, or does it make more sense to have that log / check later (like after loading the metakg)?

## Blocking Problems

- Creative-mode: it'll run because initially no ID-expansion happens. However, as the templates run, ID-expansion is done. 
    - First noted in the EDIT section of this [post](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1257521028), also noted [here](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1260418036). 
    - Desired behavior discussed [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issuecomment-1238482553) and in[ Part A](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issue-1359693815).

<details>
<summary>console logs</summary>

At first, it proceeds since there's only 1 ID
```
  bte:biothings-explorer-trapi:main MetaKG successfully loaded! +436ms
  bte:biothings-explorer-trapi:query_graph (1) Creating edges for manager... +0ms
  bte:biothings-explorer-trapi:query_graph Query node missing categories...Looking for match... +456ms
  bte:biothings-explorer-trapi:query_graph Node categories found. Assigning value: {"ids":["MONDO:0007035"],"categories":["biolink:Disease"]} +0ms
  bte:biothings-explorer-trapi:NewQNode (1) Node "disease" has (1) entities at start. +0ms
  bte:biothings-explorer-trapi:NewQNode (1) Node "disease" expanded initial curie. {"MONDO:0007035":["MONDO:0007035"]} +0ms
  bte:biothings-explorer-trapi:query_graph Creating node... +1ms
  bte:biothings-explorer-trapi:NewQNode (1) Node "chemical" has (0) entities at start. +1ms
  bte:biothings-explorer-trapi:NewQNode "chemical" connected to "t_edge" +0ms
  bte:biothings-explorer-trapi:NewQNode "disease" connected to "t_edge" +0ms
  bte:biothings-explorer-trapi:QEdge Expanded edges: approved_to_treat,treats +0ms
  bte:biothings-explorer-trapi:QueryExecutionEdge (2) Created Edge "t_edge" Reverse = true +0ms
```

But once it starts working with the templates, the ID-expansion is done right away for each template
```
  bte:biothings-explorer-trapi:inferred-mode Query proceeding in Inferred Mode. +0ms
  bte:biothings-explorer-trapi:inferred-mode Looking up query Templates +0ms
  bte:biothings-explorer-trapi:inferred-mode Got 4 inferred query templates. +8ms
2
  bte:biothings-explorer-trapi:main Expanded ids for node creativeQueryObject: (1 ids -> 3 ids) +1s
  bte:biothings-explorer-trapi:main Start to load metakg. +0ms
```


</details>

- [RangeError](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255705465) from node-expansion module when trying to run a specific UMLS ID (also noted [here](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1260418036))

## Non-blocking issues? 

- UMLS
    - Chemicals seem to retrieve descendants that aren't chemicals. See top section of this [post](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255702533) for details. 
    - Not all semantic types have been tested…so it's not clear if the descendants are confusing for more kinds of things
- Additional behavior:
    - Can we add TRAPI-logs when ID-expansion is done (INFO level)? Something like the console logs: 
```
  bte:biothings-explorer-trapi:main Expanded ids for node n0: (1 ids -> 9 ids) +0ms
  bte:biothings-explorer-trapi:main Expanded ids for node n2: (1 ids -> 3 ids) +0ms
```
- When ID-expansion is done on a QNode, can we add `is_set: true` to that QNode's properties? This makes results easier to go through (explained with examples in this [post](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255512783))

**Comment by ericz1803** [comment]
@colleenXu I looked into the `rangeError` and it looks like it there was a loop in some of the data causing infinite recursion (probably something to do with the way I parsed the UMLS data). I pushed a change to the `node-expansion` package which should fix this issue.

**Comment by colleenXu** [comment]
I tested and agree that the specific [query](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113#issuecomment-1255705465) that was getting a RangeError is now working. 

After discussion with Andrew, we agree that this issue is mainly done. 

I'll open another higher-priority issue tomorrow with the small refinements needed to deploy this as a first attempt. I'll also open an non-critical issue on the order of ID-expansion vs node-normalization (retrieving equivalent IDs). 

We may then close this issue.

**Comment by colleenXu** [comment]
Added a [commit](https://github.com/biothings/bte_trapi_query_graph_handler/pull/113/commits/2e9b52871c5799a490a28d44a1ba935e3d546abb) to remove subclass_of hops from templates. This made some templates identical so I removed duplicates. 

Then I tested and rearranged the templates. Now it's Chem-treats-Disease first, then Chem-Gene-Disease, then Chem-Pheno-Disease.

**Comment by colleenXu** [comment]
I've reviewed the new commits and confirmed that they add the two [features](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issuecomment-1304368502) described in this post. 

This PR (together with this [one](https://github.com/biothings/bte-trapi-workspace/pull/17)) are ready for further automated testing / dev review from @tokebe...

Going to move the issues and PRs to the "review" column of the github project

**Comment by colleenXu** [comment]
Noting @rjawesome @tokebe that some automated tests are failing.

**Pull request merged**
