### PR TITLE
Check Qnode/Qedge properties

### PR DESCRIPTION
**Pull request by rjawesome**
Solves [issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/503)

### CODE REVIEW

**Comment by colleenXu** [comment]
looks like QEdge is missing some specified fields...https://github.com/NCATSTranslator/ReasonerAPI/blob/1.3/docs/reference.md#fixed-fields-11

**Comment by colleenXu** [comment]
@tokebe 

@andrewsu and I wondered if the TRAPI spec could be used, rather than hard-coded constants. BTE stores a modified TRAPI spec locally and it has the sections for [QNode](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/smartapi.yaml#L1215) and [QEdge](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/smartapi.yaml#L1259)

Note that I haven't tested this PR; I've only commented after looking at the files changed...

**Comment by colleenXu** [comment]
The previous QEdge.constraints work is likely from this stuff https://github.com/biothings/BioThings_Explorer_TRAPI/issues/302, https://github.com/biothings/BioThings_Explorer_TRAPI/issues/174#issuecomment-1147956168. I think it is currently broken, and the TRAPI spec changed it from QEdge.constraints to QEdge.attribute_constraints. 

Also, I think @tokebe would be the one to comment on whether the new commits / PR https://github.com/biothings/BioThings_Explorer_TRAPI/pull/513 make sense (I'm a bit surprised that the whole openapi spec is parsed). 

If it seems fine, then someone could go forward with testing. I wonder if anyone feels comfortable handling this? Or it can be put in the pile for me to test later :P

**Comment by tokebe** [comment]
Also @colleenXu I can handle testing when it's ready.

**Comment by tokebe** [comment]
@rjawesome Based on your changes this looks good -- if you think it's ready now then I'll do some quick testing and merge to dev for final testing.

One nitpick prior to that, however: I'd prefer BTE's logs to be less "human" to fit with the general tone of the rest of our logs (`We've encountered X` -> `Encountered X`/`We will ignore X` -> `X will be ignored`, along those lines).

**Comment by tokebe** [comment]
Please do, I'll get testing in the meantime.

**Comment by rjawesome** [comment]
Logs fixed

**Pull request merged**
