### PR TITLE
add disease/phenotypic feature conflation

### PR DESCRIPTION
**Pull request by rjawesome**
Meant to fix [this issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/462)

### CODE REVIEW

**Comment by tokebe** [comment]
Code looks good to me, will merge after some quick testing.

**Comment by tokebe** [comment]
PR tests fine. However, for consistency's sake, it would be best to move this logic to [`TRAPIQueryHandler.setQueryGraph()`](https://github.com/biothings/bte_trapi_query_graph_handler/blob/72151319c5a33cd8e61e26594b0994d196111d00/src/index.js#L61-L77), where previous implementation of gene-protein conflation exists. Sorry for the extra step there!

**Comment by colleenXu** [comment]
Does it need testing after the move? And do I need to test?

**Comment by tokebe** [comment]
> I suppose if we wanted consistency it would be possible to move the gene-protein conflation.

@rjawesome That would be better actually -- please do so.

@colleenXu I'll run another quick test after, but I don't think you have to worry about testing this one.

**Comment by rjawesome** [comment]
@tokebe Gene-Protein Conflation has been moved!

**Pull request merged**
