### PR TITLE
Check metakg before query execution and cancel on missing operations

### PR DESCRIPTION
**Pull request by tokebe**
*(addresses https://github.com/biothings/BioThings_Explorer_TRAPI/issues/335, new PR/branch re-created due to broken rebase)*

Original PR here: https://github.com/biothings/bte_trapi_query_graph_handler/pull/66

Query edges are iterated over and checked against the metakg to ensure there are SmartAPI edges that correspond. On each edge iteration, it is assumed that the edge returned results so that the next edge may be reversed as needed (should resolve https://github.com/biothings/bte_trapi_query_graph_handler/pull/66#issuecomment-961482689).

### CODE REVIEW

**Comment by colleenXu** [comment]
Might want to check the automated tests for this repo, I think I see two failing...

**Comment by colleenXu** [comment]
@tokebe I'm not sure that this code is actually working? It seems to stall after some step to iterate / generate mock queryEdges to check against the metaKG...

Example: it just seems to stall after this set of logs

```
  bte:biothings-explorer-trapi:main MetaKG successfully loaded! +34ms
  bte:biothings-explorer-trapi:query_graph (1) Creating edges for manager... +0ms
  bte:biothings-explorer-trapi:query_graph Creating node... +1ms
  bte:biothings-explorer-trapi:NewQNode (1) Node "n0" has (1) entities at start. +0ms
  bte:biothings-explorer-trapi:NewQNode (1) Node "n0" expanded initial curie. {"MONDO:0020763":["MONDO:0020763"]} +0ms
  bte:biothings-explorer-trapi:query_graph Creating node... +0ms
  bte:biothings-explorer-trapi:NewQNode (1) Node "n1" has (0) entities at start. +0ms
  bte:biothings-explorer-trapi:NewQNode "n0" connected to "e1" +1ms
  bte:biothings-explorer-trapi:NewQNode "n1" connected to "e1" +0ms
  bte:biothings-explorer-trapi:UpdatedExeEdge (2) Created Edge "e1" Reverse = false +0ms
  bte:biothings-explorer-trapi:main (3) All edges created {"0":[{"qEdge":{"id":"e1","subject":{"id":"n0","category":["biolink:Disease"],"curie":["MONDO:0020763"],"expanded_curie":{"MONDO:0020763":["MONDO:0020763"]},"entity_count":1,"held_curie":[],"held_expanded":{},"connected_to":{}},"object":{"id":"n1","category":["biolink:PhenotypicFeature"],"expanded_curie":{},"entity_count":0,"held_curie":[],"held_expanded":{},"connected_to":{}}},"reverse":false,"input_equivalent_identifiers":{},"output_equivalent_identifiers":{},"object":{"id":"n1","category":["biolink:PhenotypicFeature"],"expanded_curie":{},"entity_count":0,"held_curie":[],"held_expanded":{},"connected_to":{}},"subject":{"id":"n0","category":["biolink:Disease"],"curie":["MONDO:0020763"],"expanded_curie":{"MONDO:0020763":["MONDO:0020763"]},"entity_count":1,"held_curie":[],"held_expanded":{},"connected_to":{}},"executed":false,"logs":[],"results":[]}]} +2ms
```

**Comment by tokebe** [comment]
@colleenXu It appears the stalling was caused by some missing imports, they must have been dropped while I was trying to fix the broken rebase. The latest commit should fix this.

**Comment by colleenXu** [comment]
Works now. I suggest this for merging / deploying to prod ASAP

**Comment by colleenXu** [comment]
@tokebe This PR will need resolving with main before merge though

**Pull request merged**
