### PR TITLE
merge additional attributes into set

### PR DESCRIPTION
**Pull request by rjawesome**
Meant to solve [this issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/463)

### CODE REVIEW

**Comment by colleenXu** [comment]
Ack, I left my prior feedback in the [issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/463#issuecomment-1194997431) on accident. Well, now I've tested with the latest commit...

And it looks good! I didn't test every single operation/MetaEdge...but I checked out pfocr, MyVariant, semmeddb, bioplanet pathway-disease and noticed improvements to all due to this fix. 

I also checked some TRAPI apis to make sure their edge-attributes weren't affected...and they seem fine.

**Review by colleenXu — APPROVED** [review]

**Comment by colleenXu** [comment]
Pausing with merging / deploying since it seems to cause an increase in edge-attributes and we're not clear why (based on automated demotests)

**Comment by rjawesome** [comment]
> Pausing with merging / deploying since it seems to cause an increase in edge-attributes and we're not clear why (based on automated demotests)

@colleenXu could you possibly send the relevant demotests queries/results so I could take a look at it?

**Comment by tokebe** [comment]
@rjawesome You can see a comparison between the baseline and with-PR [here](https://api.bte.ncats.io/demotests/compare?new=results-2022-07-29-m0&old=results-2022-08-01-m0). Those marked `"changed": true` are the ones of concern at the moment. 

I'm starting up a new baseline after some recent changes to both BTE and demotests; I'll update here with that comparison when it's ready. Hopefully the responses (or pattern of which requests are changed) will give some insight as to what could be happening.

**Comment by colleenXu** [comment]
@rjawesome (CC @tokebe and @andrewsu) I'm still interested in pushing this issue forward because I find it useful. I retested in my local instance and it fixes both of the original issues ([pfocr](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/463#issue-1297888839), [myvariant](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/463#issuecomment-1179328043)). 

However, there seems to be a bug. And I think that for each edge from a TRAPI KP, the edge-attributes are being duplicated (1 exception: the edge-attribute we add to say the edge is also from `aggregator_knowledge_source` BTE). 

<details>
<summary>Walk-through what I did</summary>

I reviewed the old comparison of this PR's code vs main branch code(Internal lab slack [link](https://suwulab.slack.com/archives/CC218TEKC/p1661440926719999?thread_ts=1659023041.113679&cid=CC218TEKC)), specifically the C1 run ([main](https://api.bte.ncats.io/demotests/results/results-2022-08-22-m0/C1.json) vs [PR](https://api.bte.ncats.io/demotests/results/results-2022-08-22-m2/C1.json)). I noticed that both runs only used 1 KP: COHD (which is a TRAPI KP). 

I used ARAX to look at the results for both C1 runs. For both, the first result (Calcipotriol) has an edge (aec6bbf4d95062e277502ef12948e5bd) from Calcipotriol `PUBCHEM.COMPOUND:5288783` to psoriasis `MONDO:0005083`. When you look at that edge, the main-branch run has 16 edge-attributes and the PR branch has 31 edge-attributes. Looking closer, all the edge attributes from the TRAPI KP (COHD) were duplicated. Only 1 edge-attribute isn't duplicated: the one we add to say the edge is also from `aggregator_knowledge_source` BTE. 

Looking at the demotest comparison for C1, we see that the number of edge-attributes almost doubled in the PR-branch.  
Screen Shot 2022-10-16 at 10 45 32 PM. If the pattern above holds, then 1 edge-attribute from each edge didn't duplicate and all the rest did. So `(number of original edge-attributes from main-branch run) * 2 - (number of edges) = (number of edge-attributes from PR-run)`. And that matches the math: 5920 * 2 - 370 = 11470 

</details>

**Comment by rjawesome** [comment]
@colleenXu Should be fixed with new commit. (I tested with C1.json and edge attributes seemed to go back to normal)

**Comment by colleenXu** [comment]
I tested this and it seems to work as-expected for TRAPI (automat and COHD apis) and non-TRAPI (pfocr, semmeddb, myvariant) APIs. I wasn't able to test the CHP API (it's a TRAPI one) because it gave 500 errors (server error). 

I was using my local instance with USE_THREADING = false.  

---

@tokebe could you run a demotest, trying this out? We'd expect only the size of some responses to change, and maybe a small change in the number of edge-attributes (because all records get merged and some records have more fields than others). 

You could also review this code and see if there's any issues with it?

**Comment by colleenXu** [comment]
Noting @rjawesome @tokebe that some automated tests are failing.

**Comment by rjawesome** [comment]
Not sure why integrity.test.js failing, but the graph.test.js tests have been fixed

**Comment by rjawesome** [comment]
The test you sent seems to be a specific case with ``biolink:aggregator_knowledge_source`` if I am not mistaken. I have updated in the code to merge this attribute

**Comment by colleenXu** [comment]
@tokebe I can't see the example you provided (I'm getting a 502 bad gateway). However, I think Translator-provenance stuff like "aggregator_knowledge_source" or "original_knowledge_source" may be special cases that we can leave not-merged for now. 

We may need special handling (not simple merging) for provenance stuff in the future: there's some discussion in Translator TRAPI/EPC of "nesting" this provenance stuff in the future...https://github.com/NCATSTranslator/ReasonerAPI/discussions/386

(@rjawesome we'll let you know once we make a decision on this. Then you can revert / change commits if needed)

**Comment by tokebe** [comment]
Meeting with @colleenXu 

- Don't merge unpacked edge-attributes (in the `knowledge_graph._createAttributes()`, the first branch, `if (kgEdge.attributes['edge-attributes'])` should not do any merging of any attributes being unpacked from that attribute (essentially, just revert the changes to that branch).

**Comment by rjawesome** [comment]
Done. I also added some tests for the general attribute merging behavior.

**Comment by tokebe** [comment]
`rebase`'d from main after a test fix thinking it wouldn't overcomplicate the commit history...learned my lesson there haha. But, it didn't change anything in the PR and now the tests pass, so yay.

**Pull request merged**
