### PR TITLE
Keep and trim results after reaching creative-limit

### PR DESCRIPTION
**Pull request by tokebe**
*(addresses https://github.com/biothings/BioThings_Explorer_TRAPI/issues/480)*

- If 1500 is reached, skip remaining templates, but don't discard results, instead merge them
- After execution, truncate results to top 1500, then prune knowledge graph
- More informative warning

### CODE REVIEW

**Comment by colleenXu** [comment]
Andrew and I suggest changing the limit to 1000 (matching the "first" limit of previous creative-mode limit-stuff X). That way when we see 1000 results, we are pretty certain that the limit was met/exceeded and that's why execution stopped. 

At the moment, we will see results between 1000-1500 and be unsure of what happened (usually, not all templates ran - just enough templates ran to hit 1000 results).

**Comment by colleenXu** [comment]
I'm testing a local change to do the 1000 limit right now

**Comment by colleenXu** [comment]
An odd issue, since similar queries don't seem to have this issue. 

<details>
<summary>A query with an issue: this one stops at 502 results and I don't know why...</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "disease": {
                    "ids": ["MONDO:0007739"]
                },
                "chemical": {
                    "categories": ["biolink:ChemicalEntity"]
                }
            },
            "edges": {
                "t_edge": {
                    "object": "disease",
                    "subject": "chemical",
                    "predicates": ["biolink:treats"],
                    "knowledge_type": "inferred"
                }
            }
        }
    }
}
```

</details>

A related log:
```
        {
            "timestamp": "2022-08-16T02:05:16.969Z",
            "level": "INFO",
            "message": "Addition of 502 results from Template 0 would exceed absolute maximum of 1000. After combination, response will be truncated to 1000 top results. Skipping remaining 3 templates.",
            "code": null
        },
```

**Comment by tokebe** [comment]
I've pushed a change: Now, whenever the 1000 limit is met or exceeded (after merging) execution stops. Regardless of how far over the 1000 limit, results are truncated to the top 1000 and the kg is trimmed accordingly.

**Pull request merged**
