### PR TITLE
is_set and KGEdgeID

### PR DESCRIPTION
**Pull request by ariutta**
This is a draft pull request intended to better handle consolidation of results, including these two cases:
1. when `is_set = true`: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/341.
2. when there are multiple edges connecting the same two node primaryIDs. Some bugs for this case were fixed by the updated consolidation logic, but to fully handle it properly, it was additionally necessary to incorporate @tokebe's fix: https://github.com/biothings/bte_trapi_query_graph_handler/pull/86. Now potentially two bugs can be closed:
   - https://github.com/biothings/BioThings_Explorer_TRAPI/issues/390
   - https://github.com/biothings/BioThings_Explorer_TRAPI/issues/386

**Items remaining** to address before this can be merged:
- [x] manual test: why do I get [0 results for C1simple](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/341#issuecomment-1026052910), but @colleenXu gets the expected 10? (Just needed to run the cron job.)
- [x] manual test: C2
- [x] manual test: D2
- [ ] automated tests: decide on how to structure the unit and integration tests for this repo (ResultsAssembly.test.js is failing) (@marcodarko)
- [ ] clean up: remove any unused files (@marcodarko)
- [ ] clean up: would it be more clear to rename [these variables](https://github.com/biothings/bte_trapi_query_graph_handler/pull/88#issuecomment-1026413433) in [query_results.js](https://github.com/biothings/bte_trapi_query_graph_handler/blob/is_set2_pr86/src/query_results.js)? (Related: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/379).
- [x] memory usage? See [this comment](https://suwulab.slack.com/archives/CC218TEKC/p1643737890981819?thread_ts=1643676120.912029&cid=CC218TEKC) from @tokebe.

### CODE REVIEW

**Comment by ariutta** [comment]
This pull request does not solve issue https://github.com/biothings/BioThings_Explorer_TRAPI/issues/390

**Comment by ariutta** [comment]
For the following query graph, this new code will correctly produce one edge binding with two ids vs. the current production code that produces one edge binding with one id:
<details>
<summary>query graph w/ one edge w/ multiple predicates...</summary>

```
{
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n1",
          "subject": "n2",
          "predicates": [
            "biolink:response_affected_by",
            "biolink:response_increased_by"
          ]   
        }   
      },  
      "nodes": {
        "n1": {
          "ids": [
            "NCBIGene:23221"
          ],  
          "categories": [
            "biolink:Gene"
          ]   
        },  
        "n2": {
          "categories": [
            "biolink:ChemicalEntity"
          ]   
        }   
      }   
    }   
  }
}
```

</details>

**Comment by ariutta** [comment]
As [previously discussed](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/341#issuecomment-1017763353), query graphs like the following are considered invalid, so it's OK in such cases that both the current production code and this new code fail to produce results:
<details>
<summary>query graph w/ two nodes, both connected by two edges, each w/ one predicate...</summary>

```
{
  "message": { 
    "query_graph": { 
      "edges": { 
        "e0": { 
          "object": "n1",
          "subject": "n2",
          "predicates": [ 
            "biolink:response_affected_by"
          ] 
        },
        "e1": { 
          "object": "n1",
          "subject": "n2",
          "predicates": [ 
            "biolink:response_increased_by"
          ] 
        } 
      },
      "nodes": { 
        "n1": { 
          "ids": [ 
            "NCBIGene:23221"
          ],
          "categories": [ 
            "biolink:Gene"
          ] 
        },
        "n2": { 
          "categories": [ 
            "biolink:ChemicalEntity"
          ] 
        } 
      } 
    } 
  } 
}
```

</details>

**Comment by ariutta** [comment]
This pull request may solve https://github.com/biothings/BioThings_Explorer_TRAPI/issues/386

**Comment by colleenXu** [comment]
so far, I think https://github.com/biothings/BioThings_Explorer_TRAPI/issues/390 is addressed by this PR...

**Comment by colleenXu** [comment]
What I want to check now are:
* @tokebe doing an automated test on dev server to make sure caching is still working
* can the current logic handle cases when > 1 QNode has is_set=True?

**Comment by colleenXu** [comment]
Looks like C2 (has two Gene/Protein QNodes, that both have is_set=True) is working correctly now! I've attached the TRAPI response here
[C2_edgesfix_setfix.txt](https://github.com/biothings/bte_trapi_query_graph_handler/files/7963136/C2_edgesfix_setfix.txt)

An example of what the result looks like:
Screen Shot 2022-01-28 at 10 41 12 PM

**Comment by colleenXu** [comment]
haven't tested yet: this simpler C2 still has the two QNodes with is_set = True....but should be easier to understand

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:BiologicalProcess"],
                    "ids": ["GO:0022010", "UMLS:C1818586"],
                    "name": "central nervous system myelination",
                    "is_set": false,
                    "constraints": []
                },
                "n1": {
                    "categories": ["biolink:Gene","biolink:Protein"],
                    "is_set": true,
                    "constraints": []
                },
                "n2": {
                    "categories": ["biolink:Gene","biolink:Protein"],
                    "is_set": true,
                    "constraints": []
                },
                "n3": {
                    "categories": ["biolink:SmallMolecule"],
                    "ids": [
                        "CHEMBL.COMPOUND:CHEMBL134342",
                        "CHEMBL.COMPOUND:CHEMBL1431",
                        "CHEMBL.COMPOUND:CHEMBL573",
                        "CHEMBL.COMPOUND:CHEMBL1626",
                        "CHEMBL.COMPOUND:CHEMBL741",
                        "CHEMBL.COMPOUND:CHEMBL1068",
                        "CHEMBL.COMPOUND:CHEMBL1428",
                        "CHEMBL.COMPOUND:CHEMBL30008"
                    ],
                    "is_set": false,
                    "constraints": []
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"],
                    "constraints": []
                },
                "e1": {
                    "subject": "n1",
                    "object": "n2",
                    "predicates": ["biolink:genetically_interacts_with"],
                    "constraints": []
                },
                "e2": {
                    "subject": "n3",
                    "object": "n2",
                    "predicates": ["biolink:affects", "biolink:correlated_with"],
                    "constraints": []
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
tested D2 with is_set on two QNodes. This is now working! 


Screen Shot 2022-01-28 at 10 49 35 PM

<details>
<summary>Query</summary>

```

{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01"
        },
        "e01": {
          "subject": "n01",
          "object": "n02"
        }
      },
      "nodes": {
        "n00": {
          "ids": [
            "DRUGBANK:DB00215",
            "DRUGBANK:DB01175",
            "DRUGBANK:DB00472",
            "DRUGBANK:DB00176",
            "DRUGBANK:DB00715",
            "DRUGBANK:DB01104"
          ],
          "categories": ["biolink:SmallMolecule"],
          "is_set": true
        },
        "n01": {
          "categories": ["biolink:Gene"]
        },
        "n02": {
          "ids": [
              "DOID:5844", 
              "DOID:1936", 
              "DOID:3393"
            ],
          "categories": ["biolink:Disease"],
          "is_set": true
        }
      }
    }
  }
}
```
</details>

**Comment by colleenXu** [comment]
Documenting the current automated tests that are failing....

<details>
<summary>expand this</summary>

```
 FAIL  __test__/integration/ResultAssembly.test.js
  ● Testing QueryResults Module › A2a query

    TypeError: record.$edge_metadata.trapi_qEdge_obj.isReversed is not a function

       8 |
       9 |   _getInputQueryNodeID(record) {
    > 10 |     return record.$edge_metadata.trapi_qEdge_obj.isReversed()
         |                                                  ^
      11 |       ? record.$edge_metadata.trapi_qEdge_obj.getObject().getID()
      12 |       : record.$edge_metadata.trapi_qEdge_obj.getSubject().getID();
      13 |   }

      at QueryGraphHelper._getInputQueryNodeID (src/helper.js:10:50)
      at src/query_results.js:234:39
          at Array.forEach (<anonymous>)
      at QueryResult.update (src/query_results.js:232:25)
      at Object.<anonymous> (__test__/integration/ResultAssembly.test.js:14:19)

  ● Testing QueryResults Module › n0 is-set true, a1_b2_a3_a4

    TypeError: record.$edge_metadata.trapi_qEdge_obj.isReversed is not a function

       8 |
       9 |   _getInputQueryNodeID(record) {
    > 10 |     return record.$edge_metadata.trapi_qEdge_obj.isReversed()
         |                                                  ^
      11 |       ? record.$edge_metadata.trapi_qEdge_obj.getObject().getID()
      12 |       : record.$edge_metadata.trapi_qEdge_obj.getSubject().getID();
      13 |   }

      at QueryGraphHelper._getInputQueryNodeID (src/helper.js:10:50)
      at src/query_results.js:234:39
          at Array.forEach (<anonymous>)
      at QueryResult.update (src/query_results.js:232:25)
      at Object.<anonymous> (__test__/integration/ResultAssembly.test.js:34:21)

  ● Testing QueryResults Module › n0 is-set true, a1_b1_a3_a4

    TypeError: record.$edge_metadata.trapi_qEdge_obj.isReversed is not a function

       8 |
       9 |   _getInputQueryNodeID(record) {
    > 10 |     return record.$edge_metadata.trapi_qEdge_obj.isReversed()
         |                                                  ^
      11 |       ? record.$edge_metadata.trapi_qEdge_obj.getObject().getID()
      12 |       : record.$edge_metadata.trapi_qEdge_obj.getSubject().getID();
      13 |   }

      at QueryGraphHelper._getInputQueryNodeID (src/helper.js:10:50)
      at src/query_results.js:234:39
          at Array.forEach (<anonymous>)
      at QueryResult.update (src/query_results.js:232:25)
      at Object.<anonymous> (__test__/integration/ResultAssembly.test.js:54:21)

  ● Testing QueryResults Module › is-set false

    TypeError: record.$edge_metadata.trapi_qEdge_obj.isReversed is not a function

       8 |
       9 |   _getInputQueryNodeID(record) {
    > 10 |     return record.$edge_metadata.trapi_qEdge_obj.isReversed()
         |                                                  ^
      11 |       ? record.$edge_metadata.trapi_qEdge_obj.getObject().getID()
      12 |       : record.$edge_metadata.trapi_qEdge_obj.getSubject().getID();
      13 |   }

      at QueryGraphHelper._getInputQueryNodeID (src/helper.js:10:50)
      at src/query_results.js:234:39
          at Array.forEach (<anonymous>)
      at QueryResult.update (src/query_results.js:232:25)
      at Object.<anonymous> (__test__/integration/ResultAssembly.test.js:100:21)

 PASS  __test__/unittest/QueryEdge.test.js
 PASS  __test__/integration/QEdge2BTEEdgeHandler.test.js
 PASS  __test__/unittest/redisClient.test.js
 PASS  __test__/integration/integrity.test.js
 PASS  __test__/integration/TRAPIQueryHandler.test.js (5.422 s)

Test Suites: 1 failed, 1 skipped, 16 passed, 17 of 18 total
Tests:       4 failed, 3 skipped, 148 passed, 155 total
Snapshots:   0 total

```
</details>

**Comment by ariutta** [comment]
Regarding the failing tests in `ResultAssembly.test.js`, I'll leave it up to @marcodarko to decide, with feedback welcome from @tokebe, @andrewsu and anyone else interested. That file was an experiment with a different way of writing tests, but then @marcodarko had to revert some changes in helper.js, and now those tests don't work.

**Comment by marcodarko** [comment]
Those tests need to rewritten, looks like we need to create instances of the classes used, hardcoded results won't work for now.

**Comment by ariutta** [comment]
@marcodarko, would you be able to take the lead on updating those tests and removing any unused `.DSStore` files?

**Comment by ariutta** [comment]
@andrewsu and @colleenXu (and anyone else interested), any thoughts on the vocab bullet point in the first comment? We could just leave query_results.js as-is for now and do any renaming later, or we could rename a few variables now if you prefer.

**Comment by ariutta** [comment]
@tokebe, I added you to "reviewers", but I mostly just wanted to get your OK to close PR https://github.com/biothings/bte_trapi_query_graph_handler/pull/86 in favor of this one. I wasn't able to actually merge your `fix-390` branch into this one, but I manually incorporated it.

**Comment by marcodarko** [comment]
@ariutta just confirming, yes I can do that!

**Comment by colleenXu** [comment]
I'm thinking of deferring to @ariutta and @marcodarko on whether to do the vocab change in this PR vs a separate PR....I think it depends on how easy it is to do here (and whether it breaks anything)...

**Comment by ariutta** [comment]
As soon as the tests are updated and the `.DSStore` files are gone, I'm voting that this pull request be merged because it fixes multiple issues.

Regarding vocabulary, I think we should make some changes at some point, but we can do this in a subsequent PR.

Regarding memory usage, my tests don't indicate any significant difference when compared to `main`. If this is wrong, we could look into it further, but if it's no worse than what we have now, then it shouldn't be a blocker to merging this PR.

**Review by tokebe — APPROVED** [review]
Regarding integration of `fix-390` everything seems fine. I'll continue to test memory usage but I tend to agree with the current suspicion that it may be caching that's responsible rather than this PR.

**Review by colleenXu — APPROVED** [review]

**Pull request merged**
