### PR TITLE
Experimental: Use Predicate when generating KGEdgeID

### PR DESCRIPTION
**Pull request by tokebe**
Experimental fix for biothings/BioThings_Explorer_TRAPI/issues/390, requires additional testing/consideration of cases.

### CODE REVIEW

**Comment by colleenXu** [comment]
(Will be edited as I test)

* fixes the problem with the opening post. The Edge for Query 1 now has the ID 699db074caef45450c64ad853b6bc3f0, and the edge for Query 2 has a different ID fd13dcdd83ede4fdd053d4f1adce741f. Both edges show up as separate in Query 3

**Comment by colleenXu** [comment]
I'm seeing an issue with results assembly + multi-hop query. 

Query: [A2a](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.2a_expanded_RHOBTB2_twohop.json)

Notice that there are two edges w/ different predicates between these two nodes
Screen Shot 2022-01-25 at 1 37 14 PM
Screen Shot 2022-01-25 at 1 37 27 PM

But the result with those nodes only shows one of the edges 
Screen Shot 2022-01-25 at 1 41 05 PM

This is the TRAPI response saved. 
[A2a_edges_change.txt](https://github.com/biothings/bte_trapi_query_graph_handler/files/7937393/A2a_edges_change.txt)

**Comment by colleenXu** [comment]
Finding this same issue with [D1](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/D.1_parkinsons-crohns.json)

Screen Shot 2022-01-25 at 1 53 53 PM

Screen Shot 2022-01-25 at 1 54 38 PM

**Comment by ariutta** [comment]
@colleenXu, you can try [branch is_set2_pr86](https://github.com/biothings/bte_trapi_query_graph_handler/tree/is_set2_pr86) to see whether the combination solves several of the issues you've been observing. It incorporates the changes from branch `is_set2` + this pull request (branch `fix-390`). It also updates the tests to pass for this pull request.

**Comment by colleenXu** [comment]
Noting that this PR actually addresses the issue we wanted it to address https://github.com/biothings/BioThings_Explorer_TRAPI/issues/390

However, in checking it, we realized that there was another bug occurring for multiple-edges in edge-bindings, that was on the current main. That is what my earlier comments describe. 

We will likely close this PR and instead use the other PR that combines this fix with other changes (fixing is_set logic and the multiple-edges in edge-bindings issue).

**Comment by tokebe** [comment]
Closed as this has been combined into #88

**Comment by colleenXu** [comment]
@tokebe @ariutta did we want to write any tests for this behavior?

**Comment by tokebe** [comment]
@colleenXu This is a prime example for a new test utilizing frozen records, as this can be tested by setting up two otherwise identical records with differing predicates and checking if their ID differs. We could probably stand to make a couple tests for each item we're expecting to affect the hash.

**Pull request closed without merging**
