### PR TITLE
add qualifiers to creative edges

### PR DESCRIPTION
**Pull request by rjawesome**
https://github.com/biothings/biothings_explorer/issues/834
Adds qualifiers specified in a creative mode template group to its corresponding knowledge graph edges.

### CODE REVIEW

**Comment by tokebe** [comment]
This would appear to add the qualifiers from the template group rather than from the lookups generated off the query graph. We want the qualifiers from the query to BTE, rather than qualifiers from the template's matching config (as it's possible for the template group to have more qualifiers than the query it's matched to).

A simpler implementation would be to extract the qualifiers from the qedge in `createQueries()` and pass those to the `qualifiers` property you've added in the function's return (though, note, those will not be `CompactQualifiers`).

**Comment by rjawesome** [comment]
@tokebe Each KG edge can only have one set of qualifiers according to the SmartAPI specification (https://github.com/biothings/bte-server/blob/ff85c9f3a239b36acd6f132d0f6beef6f588e582/docs/smartapi.yaml#L1813).  If the KG edge qualifiers were to be changed to the query qualifiers, there could be an issue if the user specifies multiple qualifier sets in the query. In this scenario it would be unclear which qualifier set to apply to the KG edge. How should this case be handled?

**Comment by tokebe** [comment]
Perhaps it would be best to use the templateGroup qualifiers, as you've done, but filter them so only qualifiers that match a qualifier in the query edge remain? Pinging @colleenXu for opinion.

**Comment by colleenXu** [comment]
Since this is creative-mode MVP2 specific at the moment (with no plans for users to set predicate/qualifier constraints in Pathfinder or MVP1), there should always be only 1 qualifier set specified in the starting QEdge. So I don't really think that's an issue. 

I do think it's best that we exactly match the starting QEdge qualifier set when making the qualifier set for the "inferred" creative edges. 

I'm okay with whatever is simple/straightforward right now.

**Comment by tokebe** [comment]
@rjawesome's solution is actually even better than my last comment, he's set it to use the specific qualifier set matched from the template lookup, which is always a single qualifier set. So I think we're all set on that.

I'll do some final testing and get this integrated today.

**Pull request merged**
