### PR TITLE
creative-mode templates: edit for canonical predicates

### PR DESCRIPTION
**Pull request by colleenXu**
For https://github.com/biothings/BioThings_Explorer_TRAPI/issues/475

changed ordering of QNodes (and some QNodeIDs/keys), changed ordering of QEdges, flipped subject/object for some QEdges so predicate could be changed to the canonical one in biolink-model 2.4.8

---

Not tested yet: going to test locally and maybe a demotest before/after on some creative-mode queries would be helpful?

### CODE REVIEW

**Comment by tokebe** [comment]
I think local tests should be sufficient, though feel free to save some queries you’d like to see running in demotests, it’d be great to get the query list for it more focused.

**Comment by colleenXu** [comment]
Hmmm....so far I think the 2nd template is taking longer to run / getting more results. So far, this isn't affecting output since I'm doing queries where the 2nd template went over the limits (so it wasn't incorporated). 

This might be because there are more TRAPI MetaEdges in the canonical-predicate directions...

**Comment by colleenXu** [comment]
@tokebe you'll have to point me to where to put queries for demotests...

**Comment by rjawesome** [comment]
> @tokebe you'll have to point me to where to put queries for demotests...

If you want to add queries to demotests, then you can just add a json file with the query data in the queries folder.

**Comment by colleenXu** [comment]
Oops. I realized that my earlier [post](https://github.com/biothings/bte_trapi_query_graph_handler/pull/115#issuecomment-1203182013) is probably incorrect. 

It's more likely that there's some update for the MetaEdges / KGs / x-bte annotation so more stuff is returned in queries. 

A before-after demotest would probably do a better job of checking this code than my manual checking...

**Comment by colleenXu** [comment]
@tokebe update: I've tested all of these manually and I think they're fine. you can merge without doing demotests...

I think there have been changes somehow (biolink-model update, KGs / apis, MetaEdges added?) so the 2nd template (m1) gives a ton of results / takes longer now. so...that's a bit disconcerting. 

but I should get around to developing different templates soon >.<

**Pull request merged**
