### PR TITLE
Handle null predicates, ids, and categories

### PR DESCRIPTION
**Pull request by rjawesome**
Fix [issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/498)

tested on sample queries referenced in the issue. I could probably also add some tests to ensure this null behavior if necessary?

### CODE REVIEW

**Comment by tokebe** [comment]
@rjawesome Looks good, please do add a test, that would be great!

**Comment by rjawesome** [comment]
Testing has been added

**Comment by colleenXu** [comment]
Err...maybe we want more informative / different error-catching when queries aren't formed properly? Some examples using `null`:

<details>
<summary>all QNode.ids are null</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": null,
                    "categories":["biolink:Gene"]
                },
                "n1": {
                    "ids": null,
                    "categories":["biolink:ChemicalEntity", "biolink:Procedure"]
               }
            },
            "edges": {
                "e1": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

We'd like some error message saying that BTE needs at least 1 QNode with valid CURIEs on it...

We end up hitting an SRI Resolver Failure instead

console logs
```
  bte:biothings-explorer-trapi:edge-manager (3) Edge manager is managing 1 qEdges. +66ms
  bte:biothings-explorer-trapi:edge-manager (4) Edges not yet executed = 1 +0ms
  bte:biothings-explorer-trapi:edge-manager (5) Sending next edge 'e1' with NO entity count. +0ms
  bte:biothings-explorer-trapi:edge-manager Checking entity max : (0)--(0) +0ms
  bte:biothings-explorer-trapi:edge-manager (5) Checking direction of edge with one set of entities... +0ms
  bte:biothings-explorer-trapi:edge-manager 'e1' : (0) <-- (0) +0ms
  bte:biothings-explorer-trapi:main (5) Executing current edge >> "e1" +67ms
  bte:biothings-explorer-trapi:batch_edge_query Node Update Start +14s
  bte:biothings-explorer-trapi:nodeUpdateHandler Getting equivalent IDs... +14s
  bte:biothings-explorer-trapi:nodeUpdateHandler curies: {"MolecularEntity":[null],"SmallMolecule":[null],"NucleicAcidEntity":[null],"Exon":[null],"Transcript":[null],"RnaProduct":[null],"RnaProductIsoform":[null],"NoncodingRnaProduct":[null],"MicroRna":[null],"SiRna":[null],"CodingSequence":[null],"ChemicalMixture":[null],"MolecularMixture":[null],"Drug":[null],"ComplexMolecularMixture":[null],"ProcessedMaterial":[null],"Food":[null],"EnvironmentalFoodContaminant":[null],"FoodAdditive":[null],"Nutrient":[null],"Macronutrient":[null],"Micronutrient":[null],"Vitamin":[null],"ChemicalEntity":[null],"Procedure":[null]} +1ms
  bte:biothings-explorer-trapi:error_handler SRIResolverFailiure: SRI resolver failed: Request failed with status code 422
  bte:biothings-explorer-trapi:error_handler     at query (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/biomedical_id_resolver/built/sri.js:40:15)
  bte:biothings-explorer-trapi:error_handler     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  bte:biothings-explorer-trapi:error_handler     at async Object._resolveSRI (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/biomedical_id_resolver/built/sri.js:152:24)
  bte:biothings-explorer-trapi:error_handler     at async Object.resolveSRI (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/biomedical_id_resolver/built/index.js:35:12)
  bte:biothings-explorer-trapi:error_handler     at async NodesUpdateHandler._getEquivalentIDs (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/update_nodes.js:36:31)
  bte:biothings-explorer-trapi:error_handler     at async NodesUpdateHandler.setEquivalentIDs (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/update_nodes.js:43:31)
  bte:biothings-explorer-trapi:error_handler     at async BatchEdgeQueryHandler.query (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/batch_edge_query.js:103:9)
  bte:biothings-explorer-trapi:error_handler     at async TRAPIQueryHandler.query (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:643:32)
  bte:biothings-explorer-trapi:error_handler     at async task (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/routes/v1/query_v1.js:42:7)
  bte:biothings-explorer-trapi:error_handler     at async /Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/threading/threadHandler.js:93:38 +13s
```
</details>

**Comment by colleenXu** [comment]
Note that this query successfully runs, and I think this behavior is correct (an edge-case though):

Set ids and categories to `null` for output of 1-hop Predict (or set only ids to `null` or only categories). Will execute like `Gene X -> NamedThing`. 

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["NCBIGene:1742"],
                    "categories": null
                },
                "n1": {
                    "ids": null,
                    "categories":null
               }
            },
            "edges": {
                "e1": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

**Comment by colleenXu** [comment]
TDLR:
* this looks fine to me
* had a [question](https://github.com/biothings/bte_trapi_query_graph_handler/pull/123#issuecomment-1251713010) on incorrectly-formed queries

**Comment by rjawesome** [comment]
Will look into the request you sent.

**Comment by rjawesome** [comment]
For now, I've changed it so it doesn't throw any errors and just finishes the query (similar to if the ids were not specified rather than null). I could work on changing it to where it gives an error if no ids are present which could be more descriptive

**Comment by colleenXu** [comment]
Hmmm I think catching it as an error (at least one QNode needs to have a CURIE string in an array in the ids fields) would be better. 

I just [tested](https://github.com/biothings/bte_trapi_query_graph_handler/pull/123#issuecomment-1251713010) the case I described again. It looks like it's failing to create MetaXEdges because there aren't ids to assign as queryInputs...

<details>
<summary></summary>

some relevant console logs:
```
  bte:biothings-explorer-trapi:edge-manager (3) Edge manager is managing 1 qEdges. +0ms
  bte:biothings-explorer-trapi:edge-manager (4) Edges not yet executed = 1 +0ms
  bte:biothings-explorer-trapi:edge-manager (5) Sending next edge 'e1' with NO entity count. +1ms
  bte:biothings-explorer-trapi:edge-manager Checking entity max : (0)--(0) +0ms
  bte:biothings-explorer-trapi:edge-manager (5) Checking direction of edge with one set of entities... +0ms
  bte:biothings-explorer-trapi:edge-manager 'e1' : (0) <-- (0) +0ms
  bte:biothings-explorer-trapi:qedge2btedge Subject node is n1 +0ms


  bte:biothings-explorer-trapi:edge-manager (3) Edge manager is managing 1 qEdges. +72ms
  bte:biothings-explorer-trapi:edge-manager (4) Edges not yet executed = 1 +0ms
  bte:biothings-explorer-trapi:edge-manager (5) Sending next edge 'e1' with NO entity count. +0ms
  bte:biothings-explorer-trapi:edge-manager Checking entity max : (0)--(0) +0ms
  bte:biothings-explorer-trapi:edge-manager (5) Checking direction of edge with one set of entities... +0ms
  bte:biothings-explorer-trapi:edge-manager 'e1' : (0) <-- (0) +0ms
  bte:biothings-explorer-trapi:main (5) Executing current edge >> "e1" +75ms
  bte:biothings-explorer-trapi:batch_edge_query Node Update Start +0ms
  bte:biothings-explorer-trapi:nodeUpdateHandler Getting equivalent IDs... +0ms
  bte:biothings-explorer-trapi:nodeUpdateHandler curies: {} +0ms
  bte:biothings-explorer-trapi:nodeUpdateHandler Got Edge Equivalent IDs successfully. +0ms
  bte:biothings-explorer-trapi:batch_edge_query Node Update Success +1ms
  bte:biothings-explorer-trapi:batch_edge_query Start to convert qXEdges into APIEdges.... +0ms


  bte:biothings-explorer-trapi:qedge2btedge No metaKG found for this query batch. +0ms
  bte:biothings-explorer-trapi:batch_edge_query qEdges are successfully converted into 0 APIEdges.... +66ms
  bte:biothings-explorer-trapi:main (X) Terminating..."e1" got 0 records. +68ms
```

And the response with TRAPI logs:
```
{
    "workflow": [
        {
            "id": "lookup"
        }
    ],
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": null,
                    "categories": [
                        "biolink:Gene"
                    ]
                },
                "n1": {
                    "ids": null,
                    "categories": [
                        "biolink:ChemicalEntity",
                        "biolink:Procedure"
                    ]
                }
            },
            "edges": {
                "e1": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        },
        "knowledge_graph": {
            "nodes": {},
            "edges": {}
        },
        "results": []
    },
    "logs": [
        {
            "timestamp": "2022-09-21T05:48:57.845Z",
            "level": "WARNING",
            "message": "The following APIs were unavailable at the time of execution: Automat MyChem (ITRB PROD) (trapi v-1.3.0), CAM-KP API, Automat Covidkopkg (ITRB PROD) (trapi v-1.3.0), Service Provider TRAPI, CAM-KP API, RTX KG2 - TRAPI 1.3.0",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.846Z",
            "level": "DEBUG",
            "message": "BTE identified 2 qNodes from your query graph",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.846Z",
            "level": "DEBUG",
            "message": "BTE identified 1 qEdges from your query graph",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.922Z",
            "level": "INFO",
            "message": "Executing e1 (reversed): n0 <-- n1",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.923Z",
            "level": "DEBUG",
            "message": "REDIS cache is not enabled.",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.923Z",
            "level": "DEBUG",
            "message": "BTE is trying to find metaKG edges (smartAPI registry, x-bte annotation) connecting from MolecularEntity,SmallMolecule,NucleicAcidEntity,Exon,Transcript,RnaProduct,RnaProductIsoform,NoncodingRnaProduct,MicroRna,SiRna,CodingSequence,ChemicalMixture,MolecularMixture,Drug,ComplexMolecularMixture,ProcessedMaterial,Food,EnvironmentalFoodContaminant,FoodAdditive,Nutrient,Macronutrient,Micronutrient,Vitamin,ChemicalEntity,Procedure to Gene with predicate undefined",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.981Z",
            "level": "DEBUG",
            "message": "BTE found 297 metaKG edges corresponding to e1. These metaKG edges comes from 14 unique APIs. They are BioThings BindingDB API,BioThings DGIdb API,Multiomics Wellness KP API,Multiomics BigGIM-DrugResponse KP API,BioThings pfocr API,Text Mining Targeted Association API,MyChem.info API,BioThings SEMMEDDB API,Automat Gtopdb (ITRB PROD) (trapi v-1.3.0),Automat Cord19 (ITRB PROD) (trapi v-1.3.0),Automat hmdb (ITRB PROD) (trapi v-1.3.0),Automat Hetio (ITRB PROD) (trapi v-1.3.0),Automat CTD (ITRB PROD) (trapi v-1.3.0),Automat Pharos (ITRB PROD) (trapi v-1.3.0)",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.989Z",
            "level": "WARNING",
            "message": "BTE didn't find any metaKG for this batch. Your query terminates.",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.990Z",
            "level": "INFO",
            "message": "e1 execution: 0 queries (0 success/0 fail) and (0) cached qEdges return (0) records",
            "code": null
        },
        {
            "timestamp": "2022-09-21T05:48:57.990Z",
            "level": "WARNING",
            "message": "qEdge (e1) got 0 records. Your query terminates.",
            "code": null
        }
    ]
}
```

</details>

**Comment by tokebe** [comment]
In meeting: will wait to merge until there is an error catching situations where there are 0 `qNodeIDs` in the `qGraph`.

**Comment by rjawesome** [comment]
Done!

**Comment by colleenXu** [comment]
@tokebe Can you check if the error message fits whatever response / TRAPI standard that's needed?

The "no IDs" query is [here](https://github.com/biothings/bte_trapi_query_graph_handler/pull/123#issuecomment-1251713010). 

I get this response:

```
{
    "error": "Your input query graph is invalid",
    "more_info": "No Query Node has an ID"
}
```

**Comment by tokebe** [comment]
@colleenXu The TRAPI standard [does not specify](https://github.com/NCATSTranslator/ReasonerAPI/blob/91338a117354385d58ce0b904fb70a095fc501dd/TranslatorReasonerAPI.yaml#L109-L117) the structure of the body returned when returning a `400 Bad Request`, and this structure is in-line with other errors. 

@rjawesome Sorry for the nitpick, but the `more_info` should probably be worded like similar errors -- something to the effect of `body/message.query_graph.nodes should contain at least one node with at least one non-null id`

**Pull request merged**
