### PR TITLE
add cycle validation

### PR DESCRIPTION
**Pull request by rjawesome**
Meant to solve [this issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/378). Uses a DFS to find cycles and assumes the direction of edges doesn't matter.

### CODE REVIEW

**Comment by ariutta** [comment]
Just based on looking at the code, this appears correct. But I didn't actually run any tests.

One question: does `conNode` mean "connected node"?

**Comment by rjawesome** [comment]
Yes ``conNode`` means a connected node to the current node in the DFS (depth-first search), just for anyone interested I'll give a quick summary of the algorithm. 

- For each node, create an object which contains a property of whether it has been visited and a list of connected nodes.
- Loop through all nodes
    - if this node has been visited, then continue
    - Complete a DFS starting at this node using a stack
        - If at any stage, a connected node that is not the parent node has already been visited, then we can detect a cycle

I also did some tests with the following query graphs, where queryGraph1 and queryGraph2 should be considered cycles and queryGraph3 and queryGraph4 should not be considered cycles.
<details>
<summary>Query Graphs</summary>

```javascript
const queryGraph1 = 
{
	"nodes": {
		"n0": {
			"ids":["PUBCHEM.COMPOUND:222284"],
			"categories":["biolink:ChemicalEntity"]
		},
		"n1": {
			"ids":[
				"MONDO:0005267",
				"MONDO:0005542",
				"MONDO:0005311",
				"MONDO:0005542",
				"MONDO:0004995"
				],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
	   },
		"n2": {
			"ids":["MONDO:0100096"],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
		},
		"n3": {
			"categories":["biolink:Gene"]
		}
	},
	"edges": {
		"e01": {
			"subject": "n0",
			"object": "n1",
			"predicates": ["biolink:related_to"]
		},
		"e02": {
			"subject": "n1",
			"object": "n2",
			"predicates": ["biolink:related_to"]
		},
		"e03": {
			"subject": "n0",
			"object": "n3",
			"predicates": ["biolink:related_to"]
		},
		"e04": {
			"subject": "n3",
			"object": "n2",
			"predicates": ["biolink:related_to"]
		}
	}
};

const queryGraph2 = 
{
	"nodes": {
		"n0": {
			"ids":["PUBCHEM.COMPOUND:222284"],
			"categories":["biolink:ChemicalEntity"]
		},
		"n1": {
			"ids":[
				"MONDO:0005267",
				"MONDO:0005542",
				"MONDO:0005311",
				"MONDO:0005542",
				"MONDO:0004995"
				],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
	   },
		"n2": {
			"ids":["MONDO:0100096"],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
		},
		"n3": {
			"categories":["biolink:Gene"]
		}
	},
	"edges": {
		"e02": {
			"subject": "n1",
			"object": "n2",
			"predicates": ["biolink:related_to"]
		},
		"e03": {
			"subject": "n2",
			"object": "n3",
			"predicates": ["biolink:related_to"]
		},
		"e04": {
			"subject": "n3",
			"object": "n1",
			"predicates": ["biolink:related_to"]
		}
	}
};

const queryGraph3 = 
{
	"nodes": {
		"n0": {
			"ids":["PUBCHEM.COMPOUND:222284"],
			"categories":["biolink:ChemicalEntity"]
		},
		"n1": {
			"ids":[
				"MONDO:0005267",
				"MONDO:0005542",
				"MONDO:0005311",
				"MONDO:0005542",
				"MONDO:0004995"
				],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
	   },
		"n2": {
			"ids":["MONDO:0100096"],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
		},
		"n3": {
			"categories":["biolink:Gene"]
		}
	},
	"edges": {
		"e02": {
			"subject": "n1",
			"object": "n2",
			"predicates": ["biolink:related_to"]
		},
		"e03": {
			"subject": "n1",
			"object": "n3",
			"predicates": ["biolink:related_to"]
		}
	}
};

const queryGraph4 = 
{
	"nodes": {
		"n0": {
			"ids":["PUBCHEM.COMPOUND:222284"],
			"categories":["biolink:ChemicalEntity"]
		},
		"n1": {
			"ids":[
				"MONDO:0005267",
				"MONDO:0005542",
				"MONDO:0005311",
				"MONDO:0005542",
				"MONDO:0004995"
				],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
	   },
		"n2": {
			"ids":["MONDO:0100096"],
			"categories":["biolink:DiseaseOrPhenotypicFeature"]
		},
		"n3": {
			"categories":["biolink:Gene"]
		}
	},
	"edges": {
		"e02": {
			"subject": "n1",
			"object": "n2",
			"predicates": ["biolink:related_to"]
		},
		"e03": {
			"subject": "n1",
			"object": "n3",
			"predicates": ["biolink:related_to"]
		},
		"e05": {
			"subject": "n2",
			"object": "n0"
		}
	}
};
```
</details>

**Comment by tokebe** [comment]
This looks great! If you could turn those test QGraphs into a couple of tests it would help with testing coverage/ongoing verification.

**Comment by rjawesome** [comment]
Tests have been added!

**Comment by tokebe** [comment]
Tagging @andrewsu @colleenXu for final approval to merge -- everything seems ready and tests pass (on local -- github tests still broken)

**Comment by andrewsu** [comment]
Looks good to me!

**Comment by colleenXu** [comment]
This is not recognized as a cycle by this code; should it be?

<details>
<summary>Disease ID <-> Disease</summary>
Screen Shot 2022-07-26 at 6 05 59 PM

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                },
                "e02": {
                    "subject": "n1",
                    "object": "n0"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0033373"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}

```
</details>

**Comment by colleenXu** [comment]
Notes on other things I tried:

<details>
<summary>self-edge</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n0"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0033373"],
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}

```
</details>

**Comment by rjawesome** [comment]
For the Disease ID <-> Disease query, my code works on the principle that direction doesn't matter, so n0 -> n1 is considered the same as n1 -> n0. If this is an issue one way to handle it would be to flag an error if there are "duplicate" edges (where n0 -> n1 and n1 -> n0 are considered equivalent). Alternatively, this could be treated as a special case.

Side Note. I fully ran that query and it seems to end in an error
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))\n    at TrapiResultsAssembler.update (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/query_results.js:239:55)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async TRAPIQueryHandler.query (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:609:9)\n    at async Object.task [as query_v1] (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/routes/v1/query_v1.js:34:13)\n    at async runTask (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/threading/taskHandler.js:12:9)
```
From other testing, this seems to be the error that comes up when cycles are passed into the results assembler, so I believe this case does need to be handled. 

Side Note #2. The actual reason it seems to be giving an error is that it expects there to be a node with one edge

**Comment by rjawesome** [comment]
For the Disease ID <-> Disease query, my code works on the principle that direction doesn't matter, so n0 -> n1 is considered the same as n1 -> n0. If this is an issue one way to handle it would be to flag an error if there are "duplicate" edges (where n0 -> n1 and n1 -> n0 are considered equivalent). Alternatively, this could be treated as a special case.

Side Note. I fully ran that query and it seems to end in an error
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))\n    at TrapiResultsAssembler.update (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/query_results.js:239:55)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async TRAPIQueryHandler.query (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:609:9)\n    at async Object.task [as query_v1] (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/routes/v1/query_v1.js:34:13)\n    at async runTask (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/threading/taskHandler.js:12:9)
```
From other testing, this seems to be the error that comes up when cycles are passed into the results assembler, so I believe this case does need to be handled. 

Side Note #2. The actual reason it seems to be giving an error is that it expects there to be a node with one edge

**Comment by colleenXu** [comment]
I agree! do you think this bundled into this PR / issue, or should it be something separate?

**Comment by rjawesome** [comment]
Since the code would basically be in the same place, I can probably put it into this PR and add an additional test for that case.

**Comment by tokebe** [comment]
It's probably worth making it a separate function.

**Comment by rjawesome** [comment]
New commit should fix that query, and includes an additional test

**Comment by colleenXu** [comment]
looks good to me now! 

(again, I didn't fully execute anything, I only started querying and stopped execution if it looked like it passed the checkpoint for raising the "cycle" error...)

**Comment by colleenXu** [comment]
looks good to me now! @tokebe 

(again, I didn't fully execute anything, I only started querying and stopped execution if it looked like it passed the checkpoint for raising the "cycle" error...)

**Pull request merged**
